-- AUTO-GENERATED from packages/core/src/errors.ts by scripts/error-codes.mjs.
-- Do not edit by hand. Run `npm run gen:error-codes` to regenerate.

return {
  BRIDGE_NOT_RUNNING      = "BRIDGE_NOT_RUNNING",
  BRIDGE_TIMEOUT          = "BRIDGE_TIMEOUT",
  INTERNAL_ERROR          = "INTERNAL_ERROR",
  ITEM_NOT_FOUND          = "ITEM_NOT_FOUND",
  MEDIA_NOT_FOUND         = "MEDIA_NOT_FOUND",
  OUTPUT_DIR_MISSING      = "OUTPUT_DIR_MISSING",
  OUTPUT_DIR_NOT_WRITABLE = "OUTPUT_DIR_NOT_WRITABLE",
  OUTPUT_FILE_EXISTS      = "OUTPUT_FILE_EXISTS",
  PARAMS_INVALID          = "PARAMS_INVALID",
  REF_INVALID             = "REF_INVALID",
  REGION_NAME_INVALID     = "REGION_NAME_INVALID",
  REGION_NAME_TAKEN       = "REGION_NAME_TAKEN",
  REGION_NOT_FOUND        = "REGION_NOT_FOUND",
  RENDER_FILE_EMPTY       = "RENDER_FILE_EMPTY",
  RENDER_TIMEOUT          = "RENDER_TIMEOUT",
  RESPONSE_TOO_LARGE      = "RESPONSE_TOO_LARGE",
  RISK_BLOCKED            = "RISK_BLOCKED",
  SCOPE_NOT_IMPLEMENTED   = "SCOPE_NOT_IMPLEMENTED",
  TAKE_NOT_FOUND          = "TAKE_NOT_FOUND",
  TEMPLATE_NOT_FOUND      = "TEMPLATE_NOT_FOUND",
  TRACK_NOT_FOUND         = "TRACK_NOT_FOUND",
}
