#!/usr/bin/env node
// Streetlight setup — REAPER launcher + MCP client config artifacts.
//
// macOS verified in v0.1; Windows setup is experimental until live-smoked.
// Generates:
//   1. <REAPER Resource Path>/Scripts/Streetlight/start_bridge.lua
//      A tiny launcher that dofiles the bridge in this repo. After running
//      setup ONCE, the user must register the launcher in REAPER:
//        Actions → Show action list → ReaScript: Load... →
//        Scripts/Streetlight/start_bridge.lua → Run.
//      REAPER does NOT auto-discover scripts dropped into Scripts/; the
//      Load... step is what adds it to the Action List. Once loaded it
//      stays — search "Streetlight" / Run in future sessions.
//   2. setup-out/{claude-code.json, codex-config.toml, cursor.json}
//      MCP client config snippets with this repo's absolute path baked
//      in. The user copies the appropriate snippet into their client
//      config; setup never edits user-global MCP configs (those may
//      contain other servers — merge is too risky).
//
// Also does a read-only probe of reaper.ini for the Render-in-background
// pref and warns if OFF (the #1 cause of demo failure).
//
// CLI:
//   npm run setup
//   npm run setup -- --no-overwrite
//   npm run setup -- --reaper-resource-path /custom/path

import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";

// ─── Pure functions (testable; no I/O) ──────────────────────────────────────

/**
 * Lua text for ~/Library/Application Support/REAPER/Scripts/Streetlight/start_bridge.lua.
 * Bakes in the absolute repo path. Header tells the user this is auto-
 * generated AND how to register it in REAPER's Action List (since dropping
 * a file in Scripts/ does not auto-add it — Actions → Show action list →
 * ReaScript: Load... is the documented flow).
 *
 * Windows note: the baked Lua path uses forward slashes even on Windows.
 * REAPER accepts `C:/...` paths, and the bridge's SCRIPT_DIR resolver is
 * intentionally slash-based so sibling `packs/` files resolve without
 * touching the already-verified bridge.
 */
export function buildLauncherLua(repoAbsPath) {
  if (typeof repoAbsPath !== "string" || repoAbsPath.length === 0) {
    throw new Error("buildLauncherLua: repoAbsPath must be a non-empty string");
  }
  if (!isAbsolutePath(repoAbsPath)) {
    throw new Error(
      `buildLauncherLua: repoAbsPath must be absolute, got "${repoAbsPath}"`,
    );
  }
  const luaRepoPath = toForwardSlashPath(repoAbsPath);
  const luaRepoLiteral = luaStringLiteral(luaRepoPath);
  return `-- streetlight start_bridge.lua
--
-- AUTO-GENERATED by \`npm run setup\` in the Streetlight repo at:
--   ${luaRepoPath}
-- DO NOT EDIT BY HAND. Re-run \`npm run setup\` from the repo if its
-- absolute path changes. The bridge source itself stays in the repo
-- and is picked up via dofile — \`git pull\` does NOT require re-running
-- setup.
--
-- To register this script in REAPER's Action List (one-time, per Mac):
--   Actions → Show action list → ReaScript: Load... → pick this file.
-- After Load... it stays in the Action List; search "Streetlight" and
-- Run it whenever you want the bridge up. REAPER does NOT auto-discover
-- scripts dropped into the Scripts folder.

local repo = ${luaRepoLiteral}
local bridge = repo .. "/reaper/streetlight_bridge.lua"
local f = io.open(bridge, "r")
if not f then
  reaper.ShowConsoleMsg(
    "[streetlight] launcher: bridge not found at " .. bridge ..
    "\\n[streetlight] re-run \`npm run setup\` from the repo, or check " ..
    "the repo wasn't moved/deleted.\\n"
  )
  return
end
f:close()
dofile(bridge)
`;
}

/**
 * Build the absolute path to packages/mcp-server/dist/index.js for a given
 * repo root. The MCP client invokes this via `node <path>`.
 *
 * We emit forward slashes for MCP config snippets, including on Windows:
 * Node accepts them, JSON/TOML escaping stays simple, and users can copy
 * the same-looking path between clients.
 */
export function mcpServerEntryPath(repoAbsPath) {
  return joinPortablePath(
    repoAbsPath,
    "packages",
    "mcp-server",
    "dist",
    "index.js",
  );
}

/**
 * Stringified JSON for setup-out/claude-code.json. Single-server snippet
 * the user pastes under their Claude Code `mcpServers` block. No
 * STREETLIGHT_QUEUE_DIR env override — the bridge and the server both
 * default to ~/Library/Application Support/Streetlight/queue on macOS,
 * so an explicit env var is redundant noise (and the v0.1 macOS-only
 * stance means the default matches).
 */
export function buildClaudeCodeConfig(repoAbsPath) {
  const entry = mcpServerEntryPath(repoAbsPath);
  const config = {
    mcpServers: {
      streetlight: {
        command: "node",
        args: [entry],
      },
    },
  };
  return JSON.stringify(config, null, 2) + "\n";
}

/**
 * Stringified TOML for setup-out/codex-config.toml. TOML basic strings
 * share JSON's quote / backslash escaping rules, so JSON.stringify on
 * the path string produces a valid TOML basic string.
 */
export function buildCodexConfig(repoAbsPath) {
  const entry = mcpServerEntryPath(repoAbsPath);
  const quotedEntry = JSON.stringify(entry); // safe TOML basic string
  return `# Streetlight MCP server — generated by \`npm run setup\`
# Paste this block into your Codex config (location varies by Codex
# version; typical: ~/.codex/config.toml). If you already have other
# [mcp_servers.*] tables, just add this one alongside them.

[mcp_servers.streetlight]
command = "node"
args = [${quotedEntry}]
`;
}

/**
 * Cursor uses the same mcpServers shape as Claude Code; we mirror the
 * Claude Code config with a Cursor-flavored filename for discoverability.
 */
export function buildCursorConfig(repoAbsPath) {
  return buildClaudeCodeConfig(repoAbsPath);
}

/**
 * Parse a reaper.ini blob and return whether Render-in-background is ON.
 * REAPER stores the pref under `[reaper]` as `workrender=0|1` (other
 * keys may differ across REAPER versions, but `workrender` has been the
 * stable name through the 6.x → 7.x line per the bridge's INSTALL.md
 * comment). On any uncertainty we return "unknown" — the user can verify
 * manually.
 *
 * Returns: "ON" | "OFF" | "unknown".
 */
export function parseRenderInBackground(iniContents) {
  if (typeof iniContents !== "string") return "unknown";
  // Find the [reaper] section. The pref is global, not per-project, so
  // it lives at top level. We tolerate Windows-style \r\n line endings.
  const sectionMatch = iniContents.match(
    /^\[reaper\][^\[]*/im,
  );
  if (!sectionMatch) return "unknown";
  const section = sectionMatch[0];
  // workrender=N where N is an integer. Non-zero = ON.
  const kv = section.match(/^workrender\s*=\s*(\d+)\s*$/im);
  if (!kv) return "unknown";
  return Number(kv[1]) !== 0 ? "ON" : "OFF";
}

/**
 * Resolve REAPER's default Resource Path for the given platform + home.
 * macOS is v0.1 verified. Windows is generated as experimental until a
 * live REAPER smoke proves the path end-to-end.
 */
export function defaultReaperResourcePath(platform, homeDir, env = process.env) {
  if (platform === "darwin") {
    return path.join(homeDir, "Library", "Application Support", "REAPER");
  }
  if (platform === "win32") {
    const appData =
      env.APPDATA && env.APPDATA.trim() !== ""
        ? env.APPDATA
        : path.win32.join(homeDir, "AppData", "Roaming");
    return path.win32.join(appData, "REAPER");
  }
  if (platform !== "darwin") {
    throw new Error(
      `defaultReaperResourcePath: v0.1 setup supports macOS and experimental Windows only, got platform "${platform}". ` +
        `Use --reaper-resource-path to override, or wait for the v0.2 cross-platform resolver.`,
    );
  }
}

/**
 * Absolute path where the launcher .lua file is written.
 * `<resource>/Scripts/Streetlight/start_bridge.lua`.
 */
export function launcherInstallPath(reaperResourcePath) {
  return joinPlatformPath(
    reaperResourcePath,
    "Scripts",
    "Streetlight",
    "start_bridge.lua",
  );
}

/**
 * Absolute path to reaper.ini for read-only probing.
 */
export function reaperIniPath(reaperResourcePath) {
  return joinPlatformPath(reaperResourcePath, "reaper.ini");
}

// ─── CLI side (I/O) ─────────────────────────────────────────────────────────

function looksLikeWindowsPath(p) {
  return /^[A-Za-z]:[\\/]/.test(p) || /^\\\\/.test(p);
}

function isAbsolutePath(p) {
  return path.isAbsolute(p) || looksLikeWindowsPath(p);
}

function trimTrailingSeparators(p) {
  return p.replace(/[\\/]+$/, "");
}

function toForwardSlashPath(p) {
  return p.replace(/\\/g, "/");
}

function joinPortablePath(root, ...parts) {
  return [trimTrailingSeparators(toForwardSlashPath(root)), ...parts].join("/");
}

function joinPlatformPath(root, ...parts) {
  if (looksLikeWindowsPath(root)) {
    return path.win32.join(root, ...parts);
  }
  return path.join(root, ...parts);
}

function luaStringLiteral(s) {
  return `"${s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")}"`;
}

function parseArgs(argv) {
  const opts = { overwrite: true, reaperResourcePath: null };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--no-overwrite") {
      opts.overwrite = false;
    } else if (arg === "--reaper-resource-path") {
      const v = argv[++i];
      if (!v) throw new Error("--reaper-resource-path requires a value");
      opts.reaperResourcePath = v;
    } else if (arg.startsWith("--reaper-resource-path=")) {
      opts.reaperResourcePath = arg.slice("--reaper-resource-path=".length);
    } else if (arg === "-h" || arg === "--help") {
      opts.help = true;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return opts;
}

function printHelp() {
  process.stdout.write(`\
Streetlight setup — generate REAPER launcher + MCP config artifacts.

Usage:
  npm run setup
  npm run setup -- --no-overwrite
  npm run setup -- --reaper-resource-path /custom/REAPER

Options:
  --no-overwrite                Refuse to overwrite an existing launcher.lua.
                                Default is to overwrite (the file is marked
                                AUTO-GENERATED; safe to regenerate).
  --reaper-resource-path PATH   Override the REAPER Resource Path (defaults:
                                macOS ~/Library/Application Support/REAPER;
                                Windows %APPDATA%\\REAPER).
                                Use this if REAPER runs portable or with
                                --reapath.
  -h, --help                    Show this help.

macOS is v0.1 verified. Windows setup is experimental until live-smoked.
Run from the repo root after \`npm install\` + \`npm run build\`.
`);
}

async function exists(p) {
  try {
    await fs.stat(p);
    return true;
  } catch (e) {
    if (e && e.code === "ENOENT") return false;
    throw e;
  }
}

async function writeFileMaybe(targetPath, contents, { overwrite }) {
  const present = await exists(targetPath);
  if (present && !overwrite) {
    return { written: false, reason: "exists and --no-overwrite set" };
  }
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, contents, "utf8");
  return { written: true, reason: present ? "overwritten" : "created" };
}

async function readIniBestEffort(iniPath) {
  try {
    return await fs.readFile(iniPath, "utf8");
  } catch (e) {
    if (e && e.code === "ENOENT") return null;
    process.stderr.write(
      `[streetlight setup] could not read ${iniPath}: ${e?.message ?? e}\n`,
    );
    return null;
  }
}

async function main() {
  let opts;
  try {
    opts = parseArgs(process.argv.slice(2));
  } catch (e) {
    process.stderr.write(`[streetlight setup] ${e.message}\n\n`);
    printHelp();
    process.exit(2);
  }
  if (opts.help) {
    printHelp();
    return;
  }

  if (process.platform !== "darwin" && process.platform !== "win32") {
    process.stderr.write(
      `[streetlight setup] v0.1 setup supports macOS and experimental Windows only. Detected platform: ${process.platform}. ` +
        `See docs/ROADMAP.md § v0.2 for cross-platform plans.\n`,
    );
    process.exit(1);
  }
  if (process.platform === "win32") {
    process.stderr.write(
      `[streetlight setup] Windows support is experimental in v0.1: setup files are generated, but live REAPER smoke is not yet verified.\n`,
    );
  }

  const repoAbsPath = process.cwd();
  const distEntry = mcpServerEntryPath(repoAbsPath);
  if (!(await exists(distEntry))) {
    process.stderr.write(
      `[streetlight setup] dist not found at ${distEntry}\n` +
        `[streetlight setup] run \`npm install && npm run build\` first.\n`,
    );
    process.exit(1);
  }

  const reaperResourcePath =
    opts.reaperResourcePath ??
    defaultReaperResourcePath(process.platform, os.homedir(), process.env);

  const launcherPath = launcherInstallPath(reaperResourcePath);
  const launcherLua = buildLauncherLua(repoAbsPath);
  const launcherResult = await writeFileMaybe(launcherPath, launcherLua, {
    overwrite: opts.overwrite,
  });

  const setupOutDir = path.join(repoAbsPath, "setup-out");
  const claudePath = path.join(setupOutDir, "claude-code.json");
  const codexPath = path.join(setupOutDir, "codex-config.toml");
  const cursorPath = path.join(setupOutDir, "cursor.json");
  await writeFileMaybe(claudePath, buildClaudeCodeConfig(repoAbsPath), {
    overwrite: true,
  });
  await writeFileMaybe(codexPath, buildCodexConfig(repoAbsPath), {
    overwrite: true,
  });
  await writeFileMaybe(cursorPath, buildCursorConfig(repoAbsPath), {
    overwrite: true,
  });

  const iniContents = await readIniBestEffort(reaperIniPath(reaperResourcePath));
  const renderPref =
    iniContents === null ? "not-found" : parseRenderInBackground(iniContents);

  // ─── Print next steps ─────────────────────────────────────────────────────
  const out = process.stdout;
  out.write(`\n[streetlight setup] done.\n\n`);
  out.write(`Repo path baked into the launcher:\n  ${toForwardSlashPath(repoAbsPath)}\n\n`);

  out.write(`REAPER launcher (${launcherResult.reason}):\n  ${launcherPath}\n`);
  if (!launcherResult.written) {
    out.write(`  → skipped (${launcherResult.reason}); pass without --no-overwrite to refresh.\n`);
  }
  out.write(`\n`);

  out.write(`MCP client config artifacts (in repo):\n`);
  out.write(`  ${claudePath}\n`);
  out.write(`  ${codexPath}\n`);
  out.write(`  ${cursorPath}\n\n`);

  out.write(`Render-in-background detection (read-only probe of reaper.ini):\n`);
  if (renderPref === "ON") {
    out.write(`  ✓ ON — required for render_region.\n`);
  } else if (renderPref === "OFF") {
    out.write(
      `  ⚠ OFF — REQUIRED ON for render_region. Demo will hit BRIDGE_NOT_RUNNING.\n` +
        `    Fix: REAPER → Preferences → Audio → Rendering →\n` +
        `         "Render in background (does not apply to queued renders)" → check.\n`,
    );
  } else if (renderPref === "unknown") {
    out.write(
      `  ? unknown — could not find workrender key. Verify manually:\n` +
        `    REAPER → Preferences → Audio → Rendering → "Render in background" must be ON.\n`,
    );
  } else {
    out.write(
      `  ? reaper.ini not found at ${reaperIniPath(reaperResourcePath)}\n` +
        `    (REAPER may not have been launched yet on this Mac.)\n` +
        `    Once REAPER is launched, verify: Preferences → Audio → Rendering → "Render in background" = ON.\n`,
    );
  }
  out.write(`\n`);

  out.write(`Next steps:\n`);
  out.write(`  1. Open REAPER. (If you previously added a \`dofile(...)\`\n`);
  out.write(`     line to __startup.lua for Streetlight, REMOVE it now — the\n`);
  out.write(`     launcher replaces it. Otherwise both will load and your\n`);
  out.write(`     console will show two "bridge starting" lines per launch.)\n`);
  out.write(`  2. Actions → Show action list → ReaScript: Load... →\n`);
  out.write(`     ${launcherPath}\n`);
  out.write(`     This adds "Streetlight/start_bridge.lua" to the Action List.\n`);
  out.write(`     REAPER does NOT auto-discover scripts dropped in Scripts/;\n`);
  out.write(`     Load... is the one-time registration step.\n`);
  out.write(`  3. With it selected in the Action List, click Run. Console\n`);
  out.write(`     should print "[streetlight] bridge ready (generation N) — templates: …"\n`);
  out.write(`  4. Wire your MCP client by copying the appropriate snippet from\n`);
  out.write(`     setup-out/. Each file is ready to paste (paths already absolute).\n`);
  out.write(`  5. Ping smoke: ask your agent "Can you call streetlight ping?"\n`);
  out.write(`     Expected: { ok: true, result: { bridge: "connected", ... } }.\n`);
  if (process.platform === "win32") {
    out.write(`\nWindows note: this setup path is experimental until a live REAPER smoke passes.\n`);
  }
  out.write(`\nFull cross-Mac flow: docs/CROSS_MAC_SMOKE.md.\n`);
}

// CLI vs imported-as-module detection (standard ESM idiom).
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((e) => {
    process.stderr.write(`[streetlight setup] fatal: ${e?.stack ?? e}\n`);
    process.exit(1);
  });
}
